version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
       - "5672:5672"
       - "15672:15672"

  features:
    build:
      context: ./features
    restart: always
    depends_on:
      - rabbitmq
    volumes:
      - ./logs:/logs


  model:
    build:
      context: ./model
    restart: always
    depends_on:
      - rabbitmq
      - features
    volumes:
      - ./logs:/logs


  metric:
    build:
      context: ./metric
    restart: always
    depends_on:
      - rabbitmq
      - features
      - model
    volumes:
      - ./logs:/logs

  plot:
    build:
      context: ./plot
    depends_on:
      - rabbitmq
      - features
      - model
      - metric
    volumes:
      - ./logs:/logs